services:
  postgres:
    image: postgres:18-alpine
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:8-alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'

volumes:
  postgres:
  redisdata:
