/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  billing: {
    Billing: () => import('#app/billing/controllers/billing_controller'),
  },
  content: {
    Workspace: () => import('#app/content/controllers/workspace_controller'),
  },
  core: {
    HealthChecks: () => import('#app/core/controllers/health_checks_controller'),
  },
  identity: {
    Auth: () => import('#app/identity/controllers/auth_controller'),
  },
}
