/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BrandBrainFieldSchema extends BaseModel {
  static $columns = [
    'brandBrainSectionId',
    'createdAt',
    'id',
    'label',
    'sortOrder',
    'updatedAt',
    'value',
  ] as const
  $columns = BrandBrainFieldSchema.$columns
  @column()
  declare brandBrainSectionId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class BrandBrainSectionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'key',
    'sortOrder',
    'summary',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = BrandBrainSectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare sortOrder: number
  @column()
  declare summary: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class IdeaKeyPointSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'ideaId', 'sortOrder', 'updatedAt'] as const
  $columns = IdeaKeyPointSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ideaId: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IdeaSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'cta',
    'hook',
    'id',
    'pillar',
    'problem',
    'rating',
    'sortOrder',
    'status',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = IdeaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cta: string
  @column()
  declare hook: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare pillar: string
  @column()
  declare problem: string
  @column()
  declare rating: number
  @column()
  declare sortOrder: number
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'plan',
    'stripeCustomerId',
    'stripeSubscriptionId',
    'subscriptionStatus',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare plan: string | null
  @column()
  declare stripeCustomerId: string | null
  @column()
  declare stripeSubscriptionId: string | null
  @column()
  declare subscriptionStatus: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VideoEditingJobSchema extends BaseModel {
  static $columns = [
    'audioPath',
    'captionsPath',
    'createdAt',
    'errorMessage',
    'finalPath',
    'finishedAt',
    'id',
    'normalizedPath',
    'originalPath',
    'recordingId',
    'startedAt',
    'status',
    'transcriptPath',
    'updatedAt',
    'videoId',
  ] as const
  $columns = VideoEditingJobSchema.$columns
  @column()
  declare audioPath: string | null
  @column()
  declare captionsPath: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column()
  declare finalPath: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare normalizedPath: string | null
  @column()
  declare originalPath: string
  @column()
  declare recordingId: string
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare transcriptPath: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: string
}

export class VideoEditingTaskSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'done',
    'id',
    'label',
    'sortOrder',
    'updatedAt',
    'videoId',
  ] as const
  $columns = VideoEditingTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare done: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: string
}

export class VideoRecordingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'durationMs',
    'id',
    'label',
    'mimeType',
    'scriptId',
    'sizeBytes',
    'sortOrder',
    'startedAt',
    'stoppedAt',
    'storagePath',
    'takeId',
    'trimEndMs',
    'trimStartMs',
    'updatedAt',
    'videoId',
  ] as const
  $columns = VideoRecordingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare mimeType: string | null
  @column()
  declare scriptId: string | null
  @column()
  declare sizeBytes: number | null
  @column()
  declare sortOrder: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column.dateTime()
  declare stoppedAt: DateTime | null
  @column()
  declare storagePath: string | null
  @column()
  declare takeId: string | null
  @column()
  declare trimEndMs: number | null
  @column()
  declare trimStartMs: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: string
}

export class VideoStageSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'done',
    'id',
    'label',
    'sortOrder',
    'updatedAt',
    'videoId',
  ] as const
  $columns = VideoStageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare done: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: string
}

export class VideoSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'idea',
    'ideaId',
    'preview',
    'publish',
    'scriptAssetsNeeded',
    'scriptHook',
    'scriptOnScreenText',
    'scriptRecordingNotes',
    'scriptShotList',
    'scriptSpoken',
    'sortOrder',
    'title',
    'transcript',
    'updatedAt',
    'userId',
  ] as const
  $columns = VideoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idea: string
  @column()
  declare ideaId: string | null
  @column()
  declare preview: string
  @column()
  declare publish: string
  @column()
  declare scriptAssetsNeeded: string
  @column()
  declare scriptHook: string
  @column()
  declare scriptOnScreenText: string
  @column()
  declare scriptRecordingNotes: string
  @column()
  declare scriptShotList: string
  @column()
  declare scriptSpoken: string
  @column()
  declare sortOrder: number
  @column()
  declare title: string
  @column()
  declare transcript: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}
